const content=document.getElementById('content');const title=document.getElementById('pageTitle');
let tasks=JSON.parse(localStorage.getItem('sm_tasks')||'null')||[
{id:1,title:'DBMS Assignment',subject:'DBMS',due:'Tomorrow',priority:'High',done:false},
{id:2,title:'Calculus Revision',subject:'Mathematics',due:'Today',priority:'High',done:false},
{id:3,title:'Python Practice',subject:'Python',due:'20 Sep',priority:'Medium',done:true},
{id:4,title:'AI Mini Project',subject:'AI',due:'25 Sep',priority:'Medium',done:false}
];
let mood=localStorage.getItem('sm_mood')||'Not checked';let seconds=1500,timer=null;
const save=()=>localStorage.setItem('sm_tasks',JSON.stringify(tasks));
function render(page='home'){
 document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));
 const names={home:'Good Morning, Devadharshini 👋',planner:'AI Study Planner',tasks:'Smart Task Manager',focus:'Focus Timer',progress:'Progress Dashboard',exams:'Exams & Deadlines',chat:'StudyMate AI Assistant',mood:'Mood & Stress Check-in',profile:'Profile & Settings'};
 title.textContent=names[page]||'StudyMate AI';
 ({home:home,planner:planner,tasks:taskPage,focus:focus,progress:progress,exams:exams,chat:chat,mood:moodPage,profile:profile}[page]||home)();
}
function home(){let done=tasks.filter(t=>t.done).length;content.innerHTML=`<div class="hero"><h2>Your smart study companion</h2><p>Plan smarter, focus better and track your progress.</p><button class="btn" onclick="render('planner')">✨ Generate Study Plan</button></div>
<div class="grid"><div class="card"><div class="label">Study Hours</div><div class="stat">12.5h</div><span class="label">This week</span></div><div class="card"><div class="label">Completed Tasks</div><div class="stat">${done+17}</div><span class="label">Great progress</span></div><div class="card"><div class="label">Pending Tasks</div><div class="stat">${tasks.filter(t=>!t.done).length}</div><span class="label">Stay organized</span></div><div class="card"><div class="label">Focus Sessions</div><div class="stat">24</div><span class="label">This week</span></div></div>
<div class="grid2"><div class="card"><h3>📚 Today's Study Plan</h3><div class="plan"><span>Mathematics — Calculus</span><b>60 min</b></div><div class="plan"><span>Data Structures — Trees</span><b>45 min</b></div><div class="plan"><span>Python — Practice</span><b>30 min</b></div><button class="btn secondary" onclick="render('focus')">⏱ Quick Start Focus</button></div>
<div class="card"><h3>🤖 AI Recommendation</h3><p>Your Mathematics exam is in 5 days. Based on your progress, we recommend studying <b>Calculus for 60 minutes</b> today.</p><span class="pill">Personalized</span></div></div>`}
function planner(){content.innerHTML=`<div class="card"><h3>Tell AI about your study needs</h3><div class="form"><input class="input" id="sub" placeholder="Subjects (e.g. Maths, DBMS)"><input class="input" id="exam" type="date"><input class="input" id="hours" type="number" placeholder="Available hours/day"><select id="level"><option>Medium difficulty</option><option>Easy</option><option>Hard</option></select></div><br><button class="btn" onclick="generatePlan()">✨ Generate AI Study Plan</button></div><div id="planResult"></div>`}
function generatePlan(){document.getElementById('planResult').innerHTML=`<div class="card" style="margin-top:18px"><h3>✨ AI Generated Plan</h3><div class="plan"><span>Mathematics — Calculus revision</span><b>60 min</b></div><div class="plan"><span>DBMS — SQL practice</span><b>45 min</b></div><div class="plan"><span>Data Structures — Trees</span><b>45 min</b></div><div class="plan"><span>Python — Problem solving</span><b>30 min</b></div><p class="label">Plan is balanced according to urgency, difficulty and available study time.</p><button class="btn secondary" onclick="alert('Plan saved successfully!')">Save Plan</button></div>`}
function taskPage(){content.innerHTML=`<div class="card"><h3>Add New Task</h3><div class="form"><input class="input" id="tt" placeholder="Task title"><input class="input" id="ts" placeholder="Subject"><input class="input" id="td" placeholder="Due date"><select id="tp"><option>High</option><option>Medium</option><option>Low</option></select></div><br><button class="btn" onclick="addTask()">+ Add Task</button> <button class="btn secondary" onclick="alert('AI prioritized tasks using deadline, difficulty and importance.')">🤖 AI Prioritize</button></div><div class="card" style="margin-top:18px"><h3>My Tasks</h3>${tasks.map(t=>`<div class="task"><div><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask(${t.id})"> <b>${t.title}</b><div class="label">${t.subject} • Due ${t.due}</div></div><div><span class="pill">${t.priority}</span> <button class="btn danger" onclick="deleteTask(${t.id})">×</button></div></div>`).join('')}</div>`}
function addTask(){let t=document.getElementById('tt').value;if(!t)return alert('Enter a task title');tasks.push({id:Date.now(),title:t,subject:document.getElementById('ts').value||'General',due:document.getElementById('td').value||'Upcoming',priority:document.getElementById('tp').value,done:false});save();render('tasks')}
function toggleTask(id){let t=tasks.find(x=>x.id===id);t.done=!t.done;save();render('tasks')}function deleteTask(id){tasks=tasks.filter(x=>x.id!==id);save();render('tasks')}
function focus(){content.innerHTML=`<div class="card timer"><div class="label">Pomodoro Focus Session</div><div class="timerDisplay" id="timer">25:00</div><p>Study for 25 minutes, then take a 5-minute break.</p><button class="btn" onclick="startTimer()">▶ Start</button> <button class="btn secondary" onclick="pauseTimer()">Ⅱ Pause</button> <button class="btn secondary" onclick="resetTimer()">↻ Reset</button><hr><p class="label">Today's focus sessions: 4</p></div>`;updateTimer()}
function updateTimer(){let el=document.getElementById('timer');if(el){let m=Math.floor(seconds/60),s=seconds%60;el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}}
function startTimer(){if(timer)return;timer=setInterval(()=>{if(seconds>0){seconds--;updateTimer()}else{clearInterval(timer);timer=null;alert('Focus session complete! Take a short break.')}},1000)}
function pauseTimer(){clearInterval(timer);timer=null}function resetTimer(){pauseTimer();seconds=1500;updateTimer()}
function progress(){content.innerHTML=`<div class="grid"><div class="card"><div class="label">Weekly Study Hours</div><div class="stat">12.5h</div></div><div class="card"><div class="label">Task Completion</div><div class="stat">78%</div></div><div class="card"><div class="label">Focus Sessions</div><div class="stat">24</div></div><div class="card"><div class="label">Study Streak</div><div class="stat">7 🔥</div></div></div><div class="grid2"><div class="card"><h3>Weekly Study Hours</h3><div class="chart">${[['Mon',2],['Tue',3],['Wed',1.5],['Thu',2.5],['Fri',1],['Sat',2],['Sun',1]].map(x=>`<div class="column"><i style="height:${x[1]*45}px"></i><span>${x[0]}</span></div>`).join('')}</div></div><div class="card"><h3>Subject Progress</h3>${[['Mathematics',75],['Data Structures',60],['DBMS',80],['Python',70],['AI',55]].map(x=>`<p><b>${x[0]}</b><span class="label"> ${x[1]}%</span></p><div class="progress"><div class="bar" style="width:${x[1]}%"></div></div>`).join('')}</div></div>`}
function exams(){content.innerHTML=`<div class="grid2"><div class="card"><h3>📅 Upcoming Exams</h3><div class="exam"><span><b>Mathematics</b><br><small>21 Sep 2026</small></span><span class="pill">5 Days</span></div><div class="exam"><span><b>Python Internal Test</b><br><small>28 Sep 2026</small></span><span class="pill">12 Days</span></div></div><div class="card"><h3>⏰ Deadlines</h3><div class="exam"><span><b>DBMS Assignment</b><br><small>17 Sep 2026</small></span><span class="pill">1 Day</span></div><div class="exam"><span><b>AI Mini Project</b><br><small>25 Sep 2026</small></span><span class="pill">9 Days</span></div></div></div>`}
function chat(){content.innerHTML=`<div class="card chat"><div class="messages" id="messages"><div class="msg">Hi Devadharshini! 👋 I'm StudyMate AI. Ask me about study planning, revision or time management.</div></div><div class="chatInput"><input class="input" id="chatText" placeholder="Ask StudyMate AI..."><button class="btn" onclick="sendChat()">Send</button></div></div>`}
function sendChat(){let inp=document.getElementById('chatText'),v=inp.value.trim();if(!v)return;let m=document.getElementById('messages');m.innerHTML+=`<div class="msg user">${v}</div><div class="msg">Try breaking your goal into small sessions. For today, prioritize the nearest deadline and schedule a 25-minute focus session, followed by a short break. 📚</div>`;inp.value='';m.scrollTop=m.scrollHeight}
function moodPage(){content.innerHTML=`<div class="card"><h3>How are you feeling today?</h3><p class="label">This check-in provides general study and wellness suggestions. It does not provide medical diagnosis.</p><div class="moods">${[['😊','Happy'],['🙂','Normal'],['😴','Tired'],['😟','Stressed'],['😰','Anxious']].map(x=>`<button class="mood" onclick="saveMood('${x[1]}')">${x[0]}<br><b>${x[1]}</b></button>`).join('')}</div><br><p>Today's check-in: <b id="mood">${mood}</b></p></div>`}
function saveMood(v){mood=v;localStorage.setItem('sm_mood',v);moodPage();alert('Mood saved. Take care of your study pace today!')}
function profile(){content.innerHTML=`<div class="card"><h3>👤 Student Profile</h3><p><b>Name:</b> Devadharshini M</p><p><b>Department:</b> B.E CSE - AIML</p><p><b>College:</b> Rathinam Technical Campus</p><p><b>Study Goal:</b> Improve consistency and exam preparation</p><hr><h3>⚙️ Settings</h3><button class="btn secondary" onclick="document.body.classList.toggle('dark')">Toggle Theme</button> <button class="btn" onclick="alert('Notifications enabled for study sessions and deadlines.')">🔔 Notifications</button></div>`}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>render(n.dataset.page)));render();